### ISSUE TITLE
Next release steps

### ISSUE THREAD

**Issue by eddelbuettel** [Rblp/Rblpapi#395]
The following checklist may help, we can expand / add entries as needed

- [x] merge [PR #394](https://github.com/Rblp/Rblpapi/pull/394) to correct `bds()`
- [x] rebase branch feature/release_3.24.6.1 following the merge
- [x] merge [PR #4](https://github.com/Rblp/blp/pull/4) in repo blp to provide current libraries (see tests passed in [issue #393](https://github.com/Rblp/blp/pull/5)), it also contains a prior small [PR #5](https://github.com/Rblp/blp/pull/5)
- [x] merge [PR #396](https://github.com/Rblp/Rblpapi/pull/394), then rebase branch feature/release_3.24.6.1
- [x] create PR off branch feature/release_3.24.6.1 and merge
- [x] encourage testing of the merged branch
- [x] roll version number etc and submit to CRAN

We could also switch to 'squash and merge' for a more linear history, I do that now in a few other releases.    Not too important though.

We could also switch to 'person A creates PR, person B approves, person A merges' which is more common.   Not too important though.

**Comment by johnlaing** [comment]
Approved and merged #394 . I rather like the process where the approver merges because it embeds the workflow in the git history itself, rather than just an artifact of the GH PR. Not a strongly held view, though.

Would you like to do the rebase for the release branch? I also have a change to submit there to fix/enhance `Makevars.win`. Once rebased I can push that up and we can have a look.

**Comment by eddelbuettel** [comment]
> I rather like the process where the approver merges because it embeds the workflow in the git history itself.

It is strictly the same.  But not 'squash-merging' we get this no matter whether it is you or me merging:

![image](https://github.com/user-attachments/assets/8e119884-a496-4e2c-85db-dbcc515e2050)

But it would put my name at the top-right for the last commit.  That is how every other GH repo I work on with various people does:  'developer' prepares PR, 'reviewer' looks it over, may demand changes, eventually approves and then 'developer' merges the branch he or she created when he or she deems appropriate.  

But we can do it differently here too if you insist.  It does not _really_ matter given the amount of changes we have here.

> Would you like to do the rebase for the release branch? 

Yes, done.

**Comment by johnlaing** [comment]
I'm comfortable that the new libraries work, so those are merged.

There's one more extra `Name` call that I found in `bsrch`. Relatedly, I figured out how to use the global example searches so we can have an example (and by extension, test case) that actually works. I'll submit a patch for both of those.

**Comment by eddelbuettel** [comment]
Made an [announcement to r-sig-finance](https://stat.ethz.ch/pipermail/r-sig-finance/2024q3/015211.html) just in case, we can let it sit and hopefully be tested for a few day.  

And then release as 0.3.15 to CRAN.

**Comment by mtkerbeR** [comment]
Thank you very much for your work on the release.
I did a few more tests using the windows binary builds linked in the announcement ... for me, everything worked as expected. 👍

**Comment by eddelbuettel** [comment]
Passed without issues in 'autoprocessing'.  Nice.

![image](https://github.com/user-attachments/assets/07da55fe-3279-4f6c-a08e-5bb9cbc6e89d)
